repo_url: https://github.com/Requisitos-de-Software/2024.1-Grupo01
repo_name: 2024.1-Grupo01

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

site_name: Grupo 01


nav:
  - Página Inicial: 
      - Sobre: index.md
      - Termo de Uso: docs/Home/termoDeUso.md
  - Apresentações:
      - Apresentação 1: apresentacao/apresentacao1.md
  - Reuniões:
      - Reunião 1: reuniao/reuniao1.md
  - Planejamento:
    - Cronograma: planejamento/cronograma.md
    - Heatmap: planejamento/heatmap.md
    - Ferramentas: planejamento/ferramentas.md
  - Pré-Rastreabilidade:
    - Rich Picture: pre-rastreabilidade/rich-picture.md


theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:

    # Palette toggle for automatic mode
    #- media: "(prefers-color-scheme)"
     # toggle:
      #  icon: material/brightness-auto
       # name: Mudar para o modo claro

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: claro 
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Mudar para a preferência do sistema

  language: pt-BR
  favicon: assets/logoWhite.png
  logo: assets/logoWhite.png

extra:
  version:
    provider: mike

extra_css: [stylesheets/style.css]