repo_url: https://github.com/Requisitos-de-Software/2024.1-Grupo01
repo_name: 2024.1-Grupo01

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

site_name: Grupo 01


nav:
  - Início: index.md
  - Apresentações:
      - Apresentação 1: apresentacao/apresentacao1.md
      - Apresentação 2: apresentacao/apresentacao2.md
  - Reuniões:
      - Reunião 1: reuniao/reuniao1.md
      - Reunião 2: reuniao/reuniao2.md
      - Reunião 3: reuniao/reuniao3.md
  - Planejamento:
    - Cronograma: planejamento/cronograma.md
    - Heatmap: planejamento/heatmap.md
    - Ferramentas: planejamento/ferramentas.md
    - APPs Avaliados: planejamento/appsavaliados.md
    - APP escolhido: planejamento/appescolhido.md
  - Pré-Rastreabilidade:
    - Rich Picture: pre-rastreabilidade/rich-picture.md
  - Elicitação:
    - Perfil dos Usuários: elicitacao/perfilUsuario.md
    - Priorização: elicitacao/priorizacao.md
    - Personas: elicitacao/personas.md
    - Técnicas: 
      - Introspecção: elicitacao/tecnicas/introspeccao.md
      - Observação: elicitacao/tecnicas/observacao.md
      - Analise de Interface: elicitacao/tecnicas/analise-de-interface.md
  - Termo de Uso: termoDeUso.md


theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:

    # Palette toggle for automatic mode
    #- media: "(prefers-color-scheme)"
     # toggle:
      #  icon: material/brightness-auto
       # name: Mudar para o modo claro

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: claro 
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Mudar para a preferência do sistema

  language: pt-BR
  # favicon: assets/logoWhite.png
  # logo: assets/logoWhite.png

extra:
  version:
    provider: mike

extra_css: [stylesheets/style.css]
